# Generated by Django 4.2 on 2023-04-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_author_recipestep_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ratings',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2, null=True),
        ),
    ]
